name: maciekszymanik
favicon: null
layout_spectrum: 0.17099183751270175
typography_spectrum: 0.0963151438627392
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.579034484224394
  lightness: 0.852093349210918
  saturation: 0.18510456453077495
  rhythmicContrast: 0.6662211732473224
purpose: []
